### ISSUE TITLE
Versioning support

### ISSUE THREAD

**Issue by VladimirShitov** [CostaLab/PILOT#4]
Hello! First of all, thanks for the tool and the interesting preprint. I am using PILOT in my project. However, this week, I was quite surprised to notice that my code from your previous tutorial no longer works if I install a newer version of the tool. I could have fixed the specific version in dependencies to solve this problem, but unfortunately, the version in `setup.py` was not changed along with the new API. Could you update the version along with the changes?

**Comment by mehdijoodaki** [comment]
Hello. Thank you for bringing this to our attention. We fixed it.
Please use the latest version of PILOT to apply new features (follow the tutorials) to your data.
